import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'styles/account-creation.module.css'
import AccountCreationForm from 'components/forms/create'
import Card from '@mui/material/Card'

const inter = Inter({ subsets: ['latin'] })

export default function AccountCreation() {
  return (
    <>
      <Head>
        <title>HEB ATM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <AccountCreationForm onSuccess={() => { }} onFailure={() => { }} />
        </div>
      </main>
    </>
  )
}
