import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'styles/Home.module.css'
import Button from '@mui/material/Button';
import ButtonGroup from '@mui/material/ButtonGroup'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HEB ATM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.atmCTA}>
          <Button sx={{ height: '10rem', fontWeight: 700, fontSize: '2rem' }} fullWidth={true} href="/atm" variant="contained">
            USE ATM
          </Button>
        </div>
        <div className={styles.newAccountCTA}>
          <Button sx={{ height: '10rem', fontWeight: 700, fontSize: '2rem', textAlign: 'center' }} color="secondary" fullWidth={true} href="/account-creation" variant="contained">
            Create New Account
          </Button>
        </div>
      </main >
    </>
  )
}
